/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_live555_rtsp_RTSPClient */

#ifndef _Included_com_live555_rtsp_RTSPClient
#define _Included_com_live555_rtsp_RTSPClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_live555_rtsp_RTSPClient
 * Method:    start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_live555_rtsp_RTSPClient_start
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_live555_rtsp_RTSPClient
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_live555_rtsp_RTSPClient_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
